// ---------------------------------------------------------------------------
// Windows API documentation database (MSDN style)
// Format: functionName (lowercase) -> { module, signature, description, params, retval, remarks, href }
// ---------------------------------------------------------------------------
const WINDOWS_API_DB = {
  // kernel32
  'loadlibraryw': {
    module: 'kernel32', badge: 'Win32',
    signature: 'HMODULE LoadLibraryW(\n  LPCWSTR lpLibFileName\n);',
    description: 'Loads the specified module into the address space of the calling process. The specified module may cause other modules to be loaded.',
    params: [
      { name: 'lpLibFileName', dir: '[in]', desc: 'The name of the module. This can be either a library module (a .dll file) or an executable module (an .exe file).' },
    ],
    retval: 'If the function succeeds, the return value is a handle to the module. If the function fails, the return value is NULL.',
    remarks: 'To enable or disable error messages generated by LoadLibrary, use SetErrorMode. Do not use LoadLibrary to load drivers.',
    href: 'https://learn.microsoft.com/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryw',
  },
  'loadlibraryexw': {
    module: 'kernel32', badge: 'Win32',
    signature: 'HMODULE LoadLibraryExW(\n  LPCWSTR lpLibFileName,\n  HANDLE  hFile,\n  DWORD   dwFlags\n);',
    description: 'Loads the specified module into the address space of the calling process with optional load flags.',
    params: [
      { name: 'lpLibFileName', dir: '[in]', desc: 'File name of the module to load.' },
      { name: 'hFile', dir: '[in]', desc: 'Reserved, must be NULL.' },
      { name: 'dwFlags', dir: '[in]', desc: 'Action to take when loading the module (e.g., LOAD_LIBRARY_AS_DATAFILE, LOAD_LIBRARY_SEARCH_SYSTEM32).' },
    ],
    retval: 'Handle to the loaded module, or NULL on failure.',
    remarks: 'Use GET_MODULE_HANDLE_EX_FLAG_FROM_ADDRESS with GetModuleHandleEx to pin the module.',
    href: 'https://learn.microsoft.com/windows/win32/api/libloaderapi/nf-libloaderapi-loadlibraryexw',
  },
  'freelibrary': {
    module: 'kernel32', badge: 'Win32',
    signature: 'BOOL FreeLibrary(\n  HMODULE hLibModule\n);',
    description: 'Decrements the reference count of a loaded DLL. When the count reaches zero, the module is unmapped from the address space.',
    params: [{ name: 'hLibModule', dir: '[in]', desc: 'Handle to the loaded DLL module.' }],
    retval: 'Non-zero on success, zero on failure. Call GetLastError for extended error information.',
    remarks: 'Do not call FreeLibrary from DllMain.',
    href: 'https://learn.microsoft.com/windows/win32/api/libloaderapi/nf-libloaderapi-freelibrary',
  },
  'getprocaddress': {
    module: 'kernel32', badge: 'Win32',
    signature: 'FARPROC GetProcAddress(\n  HMODULE hModule,\n  LPCSTR  lpProcName\n);',
    description: 'Retrieves the address of an exported function or variable from the specified DLL.',
    params: [
      { name: 'hModule', dir: '[in]', desc: 'Handle to the DLL that contains the function or variable.' },
      { name: 'lpProcName', dir: '[in]', desc: 'Function or variable name, or an ordinal value.' },
    ],
    retval: 'Address of the function or variable, or NULL on failure.',
    remarks: 'The spelling and case of lpProcName must match exactly the exported name.',
    href: 'https://learn.microsoft.com/windows/win32/api/libloaderapi/nf-libloaderapi-getprocaddress',
  },
  'virtualalloc': {
    module: 'kernel32', badge: 'Win32',
    signature: 'LPVOID VirtualAlloc(\n  LPVOID lpAddress,\n  SIZE_T dwSize,\n  DWORD  flAllocationType,\n  DWORD  flProtect\n);',
    description: 'Reserves, commits, or changes the state of a region of pages in the virtual address space of the calling process.',
    params: [
      { name: 'lpAddress', dir: '[in, opt]', desc: 'Starting address. If NULL, the system determines where to allocate.' },
      { name: 'dwSize', dir: '[in]', desc: 'Size of the region, in bytes.' },
      { name: 'flAllocationType', dir: '[in]', desc: 'Type of allocation (MEM_COMMIT, MEM_RESERVE, MEM_RESET, etc.).' },
      { name: 'flProtect', dir: '[in]', desc: 'Memory protection (PAGE_EXECUTE_READ, PAGE_READWRITE, etc.).' },
    ],
    retval: 'Base address of the allocated region, or NULL on failure.',
    remarks: 'Each page in a committed region occupies physical storage or the page file.',
    href: 'https://learn.microsoft.com/windows/win32/api/memoryapi/nf-memoryapi-virtualalloc',
  },
  'virtualallocex': {
    module: 'kernel32', badge: 'Win32',
    signature: 'LPVOID VirtualAllocEx(\n  HANDLE hProcess,\n  LPVOID lpAddress,\n  SIZE_T dwSize,\n  DWORD  flAllocationType,\n  DWORD  flProtect\n);',
    description: 'Reserves, commits, or changes the state of a region of memory in the virtual address space of a specified process.',
    params: [
      { name: 'hProcess', dir: '[in]', desc: 'Handle to the target process.' },
      { name: 'lpAddress', dir: '[in, opt]', desc: 'Desired starting address, or NULL.' },
      { name: 'dwSize', dir: '[in]', desc: 'Size of the region in bytes.' },
      { name: 'flAllocationType', dir: '[in]', desc: 'Allocation type flags.' },
      { name: 'flProtect', dir: '[in]', desc: 'Protection for the allocated region.' },
    ],
    retval: 'Base address of the allocated region, or NULL on failure.',
    href: 'https://learn.microsoft.com/windows/win32/api/memoryapi/nf-memoryapi-virtualallocex',
  },
  'virtualfree': {
    module: 'kernel32', badge: 'Win32',
    signature: 'BOOL VirtualFree(\n  LPVOID lpAddress,\n  SIZE_T dwSize,\n  DWORD  dwFreeType\n);',
    description: 'Releases, decommits, or releases and decommits a region of pages within the virtual address space of the calling process.',
    params: [
      { name: 'lpAddress', dir: '[in]', desc: 'Base address of the region to free.' },
      { name: 'dwSize', dir: '[in]', desc: 'Size of the region in bytes. Must be 0 when dwFreeType is MEM_RELEASE.' },
      { name: 'dwFreeType', dir: '[in]', desc: 'MEM_DECOMMIT or MEM_RELEASE.' },
    ],
    retval: 'Non-zero on success, zero on failure.',
    href: 'https://learn.microsoft.com/windows/win32/api/memoryapi/nf-memoryapi-virtualfree',
  },
  'virtualprotect': {
    module: 'kernel32', badge: 'Win32',
    signature: 'BOOL VirtualProtect(\n  LPVOID lpAddress,\n  SIZE_T dwSize,\n  DWORD  flNewProtect,\n  PDWORD lpflOldProtect\n);',
    description: 'Changes the protection on a region of committed pages in the virtual address space of the calling process.',
    params: [
      { name: 'lpAddress', dir: '[in]', desc: 'Address of the region.' },
      { name: 'dwSize', dir: '[in]', desc: 'Size of the region in bytes.' },
      { name: 'flNewProtect', dir: '[in]', desc: 'New protection value (PAGE_EXECUTE_READWRITE, etc.).' },
      { name: 'lpflOldProtect', dir: '[out]', desc: 'Receives the old protection value.' },
    ],
    retval: 'Non-zero on success, zero on failure.',
    href: 'https://learn.microsoft.com/windows/win32/api/memoryapi/nf-memoryapi-virtualprotect',
  },
  'createfilew': {
    module: 'kernel32', badge: 'Win32',
    signature: 'HANDLE CreateFileW(\n  LPCWSTR               lpFileName,\n  DWORD                 dwDesiredAccess,\n  DWORD                 dwShareMode,\n  LPSECURITY_ATTRIBUTES lpSecurityAttributes,\n  DWORD                 dwCreationDisposition,\n  DWORD                 dwFlagsAndAttributes,\n  HANDLE                hTemplateFile\n);',
    description: 'Creates or opens a file or I/O device. The most commonly used I/O devices are: file, file stream, directory, physical disk, volume, console buffer, tape drive, communications resource, mailslot, and pipe.',
    params: [
      { name: 'lpFileName', dir: '[in]', desc: 'Name of the file or device.' },
      { name: 'dwDesiredAccess', dir: '[in]', desc: 'Requested access (GENERIC_READ, GENERIC_WRITE, 0, etc.).' },
      { name: 'dwShareMode', dir: '[in]', desc: 'Sharing mode (0, FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_SHARE_DELETE).' },
      { name: 'lpSecurityAttributes', dir: '[in, opt]', desc: 'SECURITY_ATTRIBUTES or NULL.' },
      { name: 'dwCreationDisposition', dir: '[in]', desc: 'Action on existing/new file (CREATE_NEW, CREATE_ALWAYS, OPEN_EXISTING, OPEN_ALWAYS, TRUNCATE_EXISTING).' },
      { name: 'dwFlagsAndAttributes', dir: '[in]', desc: 'File or device attributes and flags.' },
      { name: 'hTemplateFile', dir: '[in, opt]', desc: 'Template file handle or NULL.' },
    ],
    retval: 'Valid handle or INVALID_HANDLE_VALUE on failure.',
    href: 'https://learn.microsoft.com/windows/win32/api/fileapi/nf-fileapi-createfilew',
  },
  'readfile': {
    module: 'kernel32', badge: 'Win32',
    signature: 'BOOL ReadFile(\n  HANDLE       hFile,\n  LPVOID       lpBuffer,\n  DWORD        nNumberOfBytesToRead,\n  LPDWORD      lpNumberOfBytesRead,\n  LPOVERLAPPED lpOverlapped\n);',
    description: 'Reads data from the specified file or input/output (I/O) device. Supports both synchronous and asynchronous operations.',
    params: [
      { name: 'hFile', dir: '[in]', desc: 'Handle to the file or device.' },
      { name: 'lpBuffer', dir: '[out]', desc: 'Pointer to the buffer that receives the data.' },
      { name: 'nNumberOfBytesToRead', dir: '[in]', desc: 'Maximum number of bytes to read.' },
      { name: 'lpNumberOfBytesRead', dir: '[out, opt]', desc: 'Receives number of bytes read. NULL for asynchronous ops.' },
      { name: 'lpOverlapped', dir: '[in, out, opt]', desc: 'OVERLAPPED structure for async I/O, or NULL.' },
    ],
    retval: 'Non-zero on success. For overlapped I/O, also check GetOverlappedResult.',
    href: 'https://learn.microsoft.com/windows/win32/api/fileapi/nf-fileapi-readfile',
  },
  'writefile': {
    module: 'kernel32', badge: 'Win32',
    signature: 'BOOL WriteFile(\n  HANDLE       hFile,\n  LPCVOID      lpBuffer,\n  DWORD        nNumberOfBytesToWrite,\n  LPDWORD      lpNumberOfBytesWritten,\n  LPOVERLAPPED lpOverlapped\n);',
    description: 'Writes data to the specified file or I/O device. Supports synchronous and asynchronous operations.',
    params: [
      { name: 'hFile', dir: '[in]', desc: 'Handle to the file or device.' },
      { name: 'lpBuffer', dir: '[in]', desc: 'Pointer to the buffer containing the data.' },
      { name: 'nNumberOfBytesToWrite', dir: '[in]', desc: 'Number of bytes to write.' },
      { name: 'lpNumberOfBytesWritten', dir: '[out, opt]', desc: 'Receives number of bytes written.' },
      { name: 'lpOverlapped', dir: '[in, out, opt]', desc: 'OVERLAPPED structure or NULL.' },
    ],
    retval: 'Non-zero on success.',
    href: 'https://learn.microsoft.com/windows/win32/api/fileapi/nf-fileapi-writefile',
  },
  'closehandle': {
    module: 'kernel32', badge: 'Win32',
    signature: 'BOOL CloseHandle(\n  HANDLE hObject\n);',
    description: 'Closes an open object handle. The system also closes the handle automatically when the process terminates.',
    params: [{ name: 'hObject', dir: '[in]', desc: 'Valid handle to an open object.' }],
    retval: 'Non-zero on success, zero on failure.',
    remarks: 'Do not close a handle more than once after CloseHandle returns non-zero.',
    href: 'https://learn.microsoft.com/windows/win32/api/handleapi/nf-handleapi-closehandle',
  },
  'createprocessw': {
    module: 'kernel32', badge: 'Win32',
    signature: 'BOOL CreateProcessW(\n  LPCWSTR               lpApplicationName,\n  LPWSTR                lpCommandLine,\n  LPSECURITY_ATTRIBUTES lpProcessAttributes,\n  LPSECURITY_ATTRIBUTES lpThreadAttributes,\n  BOOL                  bInheritHandles,\n  DWORD                 dwCreationFlags,\n  LPVOID                lpEnvironment,\n  LPCWSTR               lpCurrentDirectory,\n  LPSTARTUPINFOW        lpStartupInfo,\n  LPPROCESS_INFORMATION lpProcessInformation\n);',
    description: 'Creates a new process and its primary thread.',
    params: [
      { name: 'lpApplicationName', dir: '[in, opt]', desc: 'Module name. Can be NULL if specified in lpCommandLine.' },
      { name: 'lpCommandLine', dir: '[in, out, opt]', desc: 'Command line to execute.' },
      { name: 'lpProcessAttributes', dir: '[in, opt]', desc: 'Process security attributes.' },
      { name: 'lpThreadAttributes', dir: '[in, opt]', desc: 'Thread security attributes.' },
      { name: 'bInheritHandles', dir: '[in]', desc: 'TRUE if inheritable handles should be inherited by child.' },
      { name: 'dwCreationFlags', dir: '[in]', desc: 'Creation flags (e.g., CREATE_NEW_CONSOLE, CREATE_SUSPENDED).' },
      { name: 'lpEnvironment', dir: '[in, opt]', desc: 'Environment block or NULL to inherit.' },
      { name: 'lpCurrentDirectory', dir: '[in, opt]', desc: 'Current directory or NULL.' },
      { name: 'lpStartupInfo', dir: '[in]', desc: 'STARTUPINFO or STARTUPINFOEX structure.' },
      { name: 'lpProcessInformation', dir: '[out]', desc: 'Receives process/thread handles and IDs.' },
    ],
    retval: 'Non-zero on success. Close hProcess and hThread in PROCESS_INFORMATION when done.',
    href: 'https://learn.microsoft.com/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw',
  },
  'openprocess': {
    module: 'kernel32', badge: 'Win32',
    signature: 'HANDLE OpenProcess(\n  DWORD dwDesiredAccess,\n  BOOL  bInheritHandle,\n  DWORD dwProcessId\n);',
    description: 'Opens an existing local process object.',
    params: [
      { name: 'dwDesiredAccess', dir: '[in]', desc: 'Access rights (PROCESS_ALL_ACCESS, PROCESS_QUERY_INFORMATION, etc.).' },
      { name: 'bInheritHandle', dir: '[in]', desc: 'If TRUE, handle is inheritable.' },
      { name: 'dwProcessId', dir: '[in]', desc: 'Process identifier (PID).' },
    ],
    retval: 'Handle to the process, or NULL on failure.',
    href: 'https://learn.microsoft.com/windows/win32/api/processthreadsapi/nf-processthreadsapi-openprocess',
  },
  'heapalloc': {
    module: 'kernel32', badge: 'Win32',
    signature: 'LPVOID HeapAlloc(\n  HANDLE hHeap,\n  DWORD  dwFlags,\n  SIZE_T dwBytes\n);',
    description: 'Allocates a block of memory from a heap. The allocated memory is not movable.',
    params: [
      { name: 'hHeap', dir: '[in]', desc: 'Handle to the heap (from GetProcessHeap or HeapCreate).' },
      { name: 'dwFlags', dir: '[in]', desc: 'Allocation options (HEAP_ZERO_MEMORY, HEAP_NO_SERIALIZE, etc.).' },
      { name: 'dwBytes', dir: '[in]', desc: 'Number of bytes to allocate.' },
    ],
    retval: 'Pointer to the allocated block, or NULL if HEAP_GENERATE_EXCEPTIONS is not set.',
    href: 'https://learn.microsoft.com/windows/win32/api/heapapi/nf-heapapi-heapalloc',
  },
  'heapfree': {
    module: 'kernel32', badge: 'Win32',
    signature: 'BOOL HeapFree(\n  HANDLE  hHeap,\n  DWORD   dwFlags,\n  _Frees_ptr_opt_ LPVOID lpMem\n);',
    description: 'Frees a memory block allocated from a heap.',
    params: [
      { name: 'hHeap', dir: '[in]', desc: 'Heap handle.' },
      { name: 'dwFlags', dir: '[in]', desc: 'Heap free options (HEAP_NO_SERIALIZE or 0).' },
      { name: 'lpMem', dir: '[in, opt]', desc: 'Pointer to the memory block to free. NULL is accepted.' },
    ],
    retval: 'Non-zero on success.',
    href: 'https://learn.microsoft.com/windows/win32/api/heapapi/nf-heapapi-heapfree',
  },
  'getlasterror': {
    module: 'kernel32', badge: 'Win32',
    signature: 'DWORD GetLastError();',
    description: 'Retrieves the calling thread\'s last-error code value. The last-error code is maintained on a per-thread basis.',
    params: [],
    retval: 'The return value is the calling thread\'s last-error code.',
    remarks: 'Functions set the last-error code by calling SetLastError. Most functions set the last-error code when they fail; a few functions set it even when they succeed.',
    href: 'https://learn.microsoft.com/windows/win32/api/errhandlingapi/nf-errhandlingapi-getlasterror',
  },
  'setlasterror': {
    module: 'kernel32', badge: 'Win32',
    signature: 'void SetLastError(\n  DWORD dwErrCode\n);',
    description: 'Sets the last-error code for the calling thread.',
    params: [{ name: 'dwErrCode', dir: '[in]', desc: 'The last-error code for the thread.' }],
    retval: 'None.',
    href: 'https://learn.microsoft.com/windows/win32/api/errhandlingapi/nf-errhandlingapi-setlasterror',
  },
  'waitforsingleobject': {
    module: 'kernel32', badge: 'Win32',
    signature: 'DWORD WaitForSingleObject(\n  HANDLE hHandle,\n  DWORD  dwMilliseconds\n);',
    description: 'Waits until the specified object is in the signaled state or the time-out interval elapses.',
    params: [
      { name: 'hHandle', dir: '[in]', desc: 'Object handle (mutex, semaphore, event, thread, process, etc.).' },
      { name: 'dwMilliseconds', dir: '[in]', desc: 'Time-out interval in milliseconds. INFINITE means no timeout.' },
    ],
    retval: 'WAIT_OBJECT_0 (0), WAIT_ABANDONED (0x80), WAIT_TIMEOUT (0x102), or WAIT_FAILED (0xFFFFFFFF).',
    href: 'https://learn.microsoft.com/windows/win32/api/synchapi/nf-synchapi-waitforsingleobject',
  },
  'waitformultipleobjects': {
    module: 'kernel32', badge: 'Win32',
    signature: 'DWORD WaitForMultipleObjects(\n  DWORD        nCount,\n  const HANDLE *lpHandles,\n  BOOL         bWaitAll,\n  DWORD        dwMilliseconds\n);',
    description: 'Waits until one or all of the specified objects are in the signaled state or time-out elapses.',
    params: [
      { name: 'nCount', dir: '[in]', desc: 'Number of handles (max MAXIMUM_WAIT_OBJECTS = 64).' },
      { name: 'lpHandles', dir: '[in]', desc: 'Array of object handles.' },
      { name: 'bWaitAll', dir: '[in]', desc: 'TRUE to wait for all objects, FALSE to wait for any one.' },
      { name: 'dwMilliseconds', dir: '[in]', desc: 'Time-out interval in ms.' },
    ],
    retval: 'WAIT_OBJECT_0 through WAIT_OBJECT_0+nCount–1, WAIT_ABANDONED_0..., WAIT_TIMEOUT, or WAIT_FAILED.',
    href: 'https://learn.microsoft.com/windows/win32/api/synchapi/nf-synchapi-waitformultipleobjects',
  },
  'createthread': {
    module: 'kernel32', badge: 'Win32',
    signature: 'HANDLE CreateThread(\n  LPSECURITY_ATTRIBUTES   lpThreadAttributes,\n  SIZE_T                  dwStackSize,\n  LPTHREAD_START_ROUTINE  lpStartAddress,\n  __drv_aliasesMem LPVOID lpParameter,\n  DWORD                   dwCreationFlags,\n  LPDWORD                 lpThreadId\n);',
    description: 'Creates a thread to execute within the virtual address space of the calling process.',
    params: [
      { name: 'lpThreadAttributes', dir: '[in, opt]', desc: 'Security attributes or NULL.' },
      { name: 'dwStackSize', dir: '[in]', desc: 'Initial stack size in bytes. 0 = default.' },
      { name: 'lpStartAddress', dir: '[in]', desc: 'Thread function (LPTHREAD_START_ROUTINE).' },
      { name: 'lpParameter', dir: '[in, opt]', desc: 'Argument to pass to the thread.' },
      { name: 'dwCreationFlags', dir: '[in]', desc: 'Thread creation flags (0 or CREATE_SUSPENDED or STACK_SIZE_PARAM_IS_A_RESERVATION).' },
      { name: 'lpThreadId', dir: '[out, opt]', desc: 'Receives the thread identifier.' },
    ],
    retval: 'Handle to the new thread, or NULL on failure.',
    href: 'https://learn.microsoft.com/windows/win32/api/processthreadsapi/nf-processthreadsapi-createthread',
  },
  'terminatethread': {
    module: 'kernel32', badge: 'Win32',
    signature: 'BOOL TerminateThread(\n  HANDLE hThread,\n  DWORD  dwExitCode\n);',
    description: 'Terminates a thread. Use with extreme care; resources may not be released.',
    params: [
      { name: 'hThread', dir: '[in]', desc: 'Handle to the thread.' },
      { name: 'dwExitCode', dir: '[in]', desc: 'Exit code for the thread.' },
    ],
    retval: 'Non-zero on success, zero on failure.',
    remarks: 'TerminateThread does not allow DLL detach notifications, and thread-local storage is not cleaned up.',
    href: 'https://learn.microsoft.com/windows/win32/api/processthreadsapi/nf-processthreadsapi-terminatethread',
  },
  'getmodulefilenamew': {
    module: 'kernel32', badge: 'Win32',
    signature: 'DWORD GetModuleFileNameW(\n  HMODULE hModule,\n  LPWSTR  lpFilename,\n  DWORD   nSize\n);',
    description: 'Retrieves the fully qualified path for the file that contains the specified module.',
    params: [
      { name: 'hModule', dir: '[in, opt]', desc: 'Module handle or NULL for the current executable.' },
      { name: 'lpFilename', dir: '[out]', desc: 'Buffer to receive the path.' },
      { name: 'nSize', dir: '[in]', desc: 'Size of buffer in TCHARs.' },
    ],
    retval: 'Length of the path string in TCHARs, or 0 on failure.',
    href: 'https://learn.microsoft.com/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulefilenamew',
  },
  'getmodulehandlew': {
    module: 'kernel32', badge: 'Win32',
    signature: 'HMODULE GetModuleHandleW(\n  LPCWSTR lpModuleName\n);',
    description: 'Retrieves a module handle for the specified module. The module must have been loaded by the calling process.',
    params: [{ name: 'lpModuleName', dir: '[in, opt]', desc: 'Module name or NULL for the current executable.' }],
    retval: 'Module handle, or NULL on failure.',
    remarks: 'GetModuleHandle does not increment the module\'s reference count.',
    href: 'https://learn.microsoft.com/windows/win32/api/libloaderapi/nf-libloaderapi-getmodulehandlew',
  },
  'getexitcodeprocess': {
    module: 'kernel32', badge: 'Win32',
    signature: 'BOOL GetExitCodeProcess(\n  HANDLE  hProcess,\n  LPDWORD lpExitCode\n);',
    description: 'Retrieves the termination status of the specified process.',
    params: [
      { name: 'hProcess', dir: '[in]', desc: 'Handle to the process.' },
      { name: 'lpExitCode', dir: '[out]', desc: 'Receives the exit code, or STILL_ACTIVE (0x103) if running.' },
    ],
    retval: 'Non-zero on success.',
    href: 'https://learn.microsoft.com/windows/win32/api/processthreadsapi/nf-processthreadsapi-getexitcodeprocess',
  },
  // ntdll
  'ntmapviewofsection': {
    module: 'ntdll', badge: 'NT',
    signature: 'NTSTATUS NtMapViewOfSection(\n  HANDLE          SectionHandle,\n  HANDLE          ProcessHandle,\n  PVOID           *BaseAddress,\n  ULONG_PTR       ZeroBits,\n  SIZE_T          CommitSize,\n  PLARGE_INTEGER  SectionOffset,\n  PSIZE_T         ViewSize,\n  SECTION_INHERIT InheritDisposition,\n  ULONG           AllocationType,\n  ULONG           Win32Protect\n);',
    description: 'Maps a view of a section object into the virtual address space of a subject process.',
    params: [
      { name: 'SectionHandle', dir: '[in]', desc: 'Handle to a section object.' },
      { name: 'ProcessHandle', dir: '[in]', desc: 'Handle to the target process.' },
      { name: 'BaseAddress', dir: '[in, out]', desc: 'Desired base address (or NULL). Receives the actual base.' },
      { name: 'ZeroBits', dir: '[in]', desc: 'Number of high-order address bits that must be zero.' },
      { name: 'CommitSize', dir: '[in]', desc: 'Initial commit size in bytes.' },
      { name: 'SectionOffset', dir: '[in, out, opt]', desc: 'Offset within the section to map from.' },
      { name: 'ViewSize', dir: '[in, out]', desc: 'Size of the view in bytes.' },
      { name: 'InheritDisposition', dir: '[in]', desc: 'ViewShare or ViewUnmap.' },
      { name: 'AllocationType', dir: '[in]', desc: 'Allocation flags (MEM_LARGE_PAGES, etc.).' },
      { name: 'Win32Protect', dir: '[in]', desc: 'Protection for the mapped view (PAGE_*).' },
    ],
    retval: 'NTSTATUS code. STATUS_SUCCESS (0) on success.',
    href: 'https://learn.microsoft.com/windows-hardware/drivers/ddi/wdm/nf-wdm-zwmapviewofsection',
  },
  'ntunmapviewofsection': {
    module: 'ntdll', badge: 'NT',
    signature: 'NTSTATUS NtUnmapViewOfSection(\n  HANDLE ProcessHandle,\n  PVOID  BaseAddress\n);',
    description: 'Unmaps a view of a section from the virtual address space of a subject process.',
    params: [
      { name: 'ProcessHandle', dir: '[in]', desc: 'Handle to the process.' },
      { name: 'BaseAddress', dir: '[in, opt]', desc: 'Base address of the view to unmap.' },
    ],
    retval: 'NTSTATUS code.',
    href: 'https://learn.microsoft.com/windows-hardware/drivers/ddi/wdm/nf-wdm-zwunmapviewofsection',
  },
  'ntallocatevirtualmemory': {
    module: 'ntdll', badge: 'NT',
    signature: 'NTSTATUS NtAllocateVirtualMemory(\n  HANDLE    ProcessHandle,\n  PVOID     *BaseAddress,\n  ULONG_PTR ZeroBits,\n  PSIZE_T   RegionSize,\n  ULONG     AllocationType,\n  ULONG     Protect\n);',
    description: 'Reserves or commits a region of pages in the virtual address space of a process.',
    params: [
      { name: 'ProcessHandle', dir: '[in]', desc: 'Target process handle (NtCurrentProcess() for self).' },
      { name: 'BaseAddress', dir: '[in, out]', desc: 'Desired base address or NULL. Receives the allocated base.' },
      { name: 'ZeroBits', dir: '[in]', desc: 'Number of high-order bits that must be zero.' },
      { name: 'RegionSize', dir: '[in, out]', desc: 'Region size in bytes.' },
      { name: 'AllocationType', dir: '[in]', desc: 'MEM_COMMIT, MEM_RESERVE, etc.' },
      { name: 'Protect', dir: '[in]', desc: 'Page protection (PAGE_READWRITE, etc.).' },
    ],
    retval: 'NTSTATUS — STATUS_SUCCESS on success.',
    href: 'https://learn.microsoft.com/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntallocatevirtualmemory',
  },
  'ntfreevirtualmemory': {
    module: 'ntdll', badge: 'NT',
    signature: 'NTSTATUS NtFreeVirtualMemory(\n  HANDLE  ProcessHandle,\n  PVOID   *BaseAddress,\n  PSIZE_T RegionSize,\n  ULONG   FreeType\n);',
    description: 'Releases or decommits a region of pages in the virtual address space of a process.',
    params: [
      { name: 'ProcessHandle', dir: '[in]', desc: 'Handle to the target process.' },
      { name: 'BaseAddress', dir: '[in, out]', desc: 'Base address of the region.' },
      { name: 'RegionSize', dir: '[in, out]', desc: 'Size in bytes.' },
      { name: 'FreeType', dir: '[in]', desc: 'MEM_DECOMMIT or MEM_RELEASE.' },
    ],
    retval: 'NTSTATUS.',
    href: 'https://learn.microsoft.com/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntfreevirtualmemory',
  },
  'ntcreatefile': {
    module: 'ntdll', badge: 'NT',
    signature: 'NTSTATUS NtCreateFile(\n  PHANDLE            FileHandle,\n  ACCESS_MASK        DesiredAccess,\n  POBJECT_ATTRIBUTES ObjectAttributes,\n  PIO_STATUS_BLOCK   IoStatusBlock,\n  PLARGE_INTEGER     AllocationSize,\n  ULONG              FileAttributes,\n  ULONG              ShareAccess,\n  ULONG              CreateDisposition,\n  ULONG              CreateOptions,\n  PVOID              EaBuffer,\n  ULONG              EaLength\n);',
    description: 'Creates a new file or directory, or opens an existing file, device, directory, or volume using the NT native interface.',
    params: [
      { name: 'FileHandle', dir: '[out]', desc: 'Receives the file handle.' },
      { name: 'DesiredAccess', dir: '[in]', desc: 'Access mask (GENERIC_READ, FILE_ALL_ACCESS, etc.).' },
      { name: 'ObjectAttributes', dir: '[in]', desc: 'OBJECT_ATTRIBUTES with the file name in NT path format (\\??\\...).' },
      { name: 'IoStatusBlock', dir: '[out]', desc: 'I/O status result block.' },
      { name: 'AllocationSize', dir: '[in, opt]', desc: 'Initial file allocation size or NULL.' },
      { name: 'FileAttributes', dir: '[in]', desc: 'File attributes (FILE_ATTRIBUTE_NORMAL, etc.).' },
      { name: 'ShareAccess', dir: '[in]', desc: 'FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_SHARE_DELETE, or combination.' },
      { name: 'CreateDisposition', dir: '[in]', desc: 'FILE_OPEN, FILE_CREATE, FILE_OVERWRITE_IF, etc.' },
      { name: 'CreateOptions', dir: '[in]', desc: 'FILE_SYNCHRONOUS_IO_NONALERT, FILE_NON_DIRECTORY_FILE, etc.' },
      { name: 'EaBuffer', dir: '[in, opt]', desc: 'Extended attributes buffer or NULL.' },
      { name: 'EaLength', dir: '[in]', desc: 'Length of EaBuffer.' },
    ],
    retval: 'NTSTATUS. Check IoStatusBlock.Information for FILE_OPENED, FILE_CREATED, etc.',
    href: 'https://learn.microsoft.com/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntcreatefile',
  },
  'ntreadfile': {
    module: 'ntdll', badge: 'NT',
    signature: 'NTSTATUS NtReadFile(\n  HANDLE           FileHandle,\n  HANDLE           Event,\n  PIO_APC_ROUTINE  ApcRoutine,\n  PVOID            ApcContext,\n  PIO_STATUS_BLOCK IoStatusBlock,\n  PVOID            Buffer,\n  ULONG            Length,\n  PLARGE_INTEGER   ByteOffset,\n  PULONG           Key\n);',
    description: 'Reads data from an open file.',
    params: [
      { name: 'FileHandle', dir: '[in]', desc: 'File handle opened with FILE_READ_DATA access.' },
      { name: 'Event', dir: '[in, opt]', desc: 'Event handle signaled on completion, or NULL.' },
      { name: 'ApcRoutine', dir: '[in, opt]', desc: 'APC routine called on completion.' },
      { name: 'ApcContext', dir: '[in, opt]', desc: 'Context passed to APC.' },
      { name: 'IoStatusBlock', dir: '[out]', desc: 'Final I/O status and bytes transferred.' },
      { name: 'Buffer', dir: '[out]', desc: 'Buffer to receive the data.' },
      { name: 'Length', dir: '[in]', desc: 'Length of Buffer in bytes.' },
      { name: 'ByteOffset', dir: '[in, opt]', desc: 'File offset to read from.' },
      { name: 'Key', dir: '[in, opt]', desc: 'File lock key or NULL.' },
    ],
    retval: 'NTSTATUS. STATUS_PENDING if async.',
    href: 'https://learn.microsoft.com/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntreadfile',
  },
  'ntclose': {
    module: 'ntdll', badge: 'NT',
    signature: 'NTSTATUS NtClose(\n  HANDLE Handle\n);',
    description: 'Closes an object handle.',
    params: [{ name: 'Handle', dir: '[in]', desc: 'Handle to close.' }],
    retval: 'NTSTATUS.',
    href: 'https://learn.microsoft.com/windows-hardware/drivers/ddi/wdm/nf-wdm-zwclose',
  },
  'ntqueryvirtualmemory': {
    module: 'ntdll', badge: 'NT',
    signature: 'NTSTATUS NtQueryVirtualMemory(\n  HANDLE                   ProcessHandle,\n  PVOID                    BaseAddress,\n  MEMORY_INFORMATION_CLASS MemoryInformationClass,\n  PVOID                    MemoryInformation,\n  SIZE_T                   MemoryInformationLength,\n  PSIZE_T                  ReturnLength\n);',
    description: 'Returns information about a range of pages in the virtual address space of the specified process.',
    params: [
      { name: 'ProcessHandle', dir: '[in]', desc: 'Process handle.' },
      { name: 'BaseAddress', dir: '[in]', desc: 'Base address of the region to query.' },
      { name: 'MemoryInformationClass', dir: '[in]', desc: 'Type of information (MemoryBasicInformation, MemoryWorkingSetInformation, etc.).' },
      { name: 'MemoryInformation', dir: '[out]', desc: 'Buffer receiving the information.' },
      { name: 'MemoryInformationLength', dir: '[in]', desc: 'Size of MemoryInformation buffer.' },
      { name: 'ReturnLength', dir: '[out, opt]', desc: 'Receives the number of bytes returned.' },
    ],
    retval: 'NTSTATUS.',
    href: 'https://learn.microsoft.com/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ntqueryvirtualmemory',
  },
  'ntqueryinformationprocess': {
    module: 'ntdll', badge: 'NT',
    signature: 'NTSTATUS NtQueryInformationProcess(\n  HANDLE           ProcessHandle,\n  PROCESSINFOCLASS ProcessInformationClass,\n  PVOID            ProcessInformation,\n  ULONG            ProcessInformationLength,\n  PULONG           ReturnLength\n);',
    description: 'Retrieves information about the specified process.',
    params: [
      { name: 'ProcessHandle', dir: '[in]', desc: 'Process handle with PROCESS_QUERY_INFORMATION access.' },
      { name: 'ProcessInformationClass', dir: '[in]', desc: 'Type of information to retrieve (ProcessBasicInformation, ProcessImageFileName, etc.).' },
      { name: 'ProcessInformation', dir: '[out]', desc: 'Buffer to receive the information.' },
      { name: 'ProcessInformationLength', dir: '[in]', desc: 'Size of the buffer.' },
      { name: 'ReturnLength', dir: '[out, opt]', desc: 'Length of the returned data.' },
    ],
    retval: 'NTSTATUS.',
    remarks: 'Many information classes are undocumented; ProcessBasicInformation (0) is the most commonly used.',
    href: 'https://learn.microsoft.com/windows/win32/api/winternl/nf-winternl-ntqueryinformationprocess',
  },
  'ldrloaddll': {
    module: 'ntdll', badge: 'NT',
    signature: 'NTSTATUS LdrLoadDll(\n  PWSTR            DllPath,\n  PULONG           DllCharacteristics,\n  PUNICODE_STRING  DllName,\n  PVOID            *DllHandle\n);',
    description: 'Loads a DLL into the calling process\'s address space. This is the internal loader function that LoadLibrary ultimately calls.',
    params: [
      { name: 'DllPath', dir: '[in, opt]', desc: 'Search path override, or NULL to use normal search order.' },
      { name: 'DllCharacteristics', dir: '[in, opt]', desc: 'Optional DLL characteristics flag.' },
      { name: 'DllName', dir: '[in]', desc: 'UNICODE_STRING containing the DLL name.' },
      { name: 'DllHandle', dir: '[out]', desc: 'Receives the module base address/handle.' },
    ],
    retval: 'NTSTATUS.',
    href: 'https://learn.microsoft.com/windows-hardware/drivers/ddi/ntifs/nf-ntifs-ldrloaddll',
  },
  'rtlallocateheap': {
    module: 'ntdll', badge: 'NT',
    signature: 'PVOID RtlAllocateHeap(\n  PVOID  HeapHandle,\n  ULONG  Flags,\n  SIZE_T Size\n);',
    description: 'Allocates a block of memory from a specified heap. Called internally by HeapAlloc.',
    params: [
      { name: 'HeapHandle', dir: '[in]', desc: 'Handle to the heap.' },
      { name: 'Flags', dir: '[in]', desc: 'Allocation flags (HEAP_ZERO_MEMORY, etc.).' },
      { name: 'Size', dir: '[in]', desc: 'Number of bytes to allocate.' },
    ],
    retval: 'Pointer to the allocated block, or NULL on failure.',
    href: 'https://learn.microsoft.com/windows-hardware/drivers/ddi/ntifs/nf-ntifs-rtlallocateheap',
  },
  'rtlfreeheap': {
    module: 'ntdll', badge: 'NT',
    signature: 'BOOLEAN RtlFreeHeap(\n  PVOID HeapHandle,\n  ULONG Flags,\n  PVOID BaseAddress\n);',
    description: 'Frees a memory block allocated from a heap. Called internally by HeapFree.',
    params: [
      { name: 'HeapHandle', dir: '[in]', desc: 'Heap handle.' },
      { name: 'Flags', dir: '[in]', desc: 'Heap free flags.' },
      { name: 'BaseAddress', dir: '[in]', desc: 'Pointer to the block to free.' },
    ],
    retval: 'TRUE on success, FALSE on failure.',
    href: 'https://learn.microsoft.com/windows-hardware/drivers/ddi/ntifs/nf-ntifs-rtlfreeheap',
  },
  'ntquerysysteminformation': {
    module: 'ntdll', badge: 'NT',
    signature: 'NTSTATUS NtQuerySystemInformation(\n  SYSTEM_INFORMATION_CLASS SystemInformationClass,\n  PVOID                    SystemInformation,\n  ULONG                    SystemInformationLength,\n  PULONG                   ReturnLength\n);',
    description: 'Retrieves specified system information.',
    params: [
      { name: 'SystemInformationClass', dir: '[in]', desc: 'Class of information (SystemBasicInformation, SystemProcessInformation, etc.).' },
      { name: 'SystemInformation', dir: '[out]', desc: 'Buffer to receive the information.' },
      { name: 'SystemInformationLength', dir: '[in]', desc: 'Buffer size in bytes.' },
      { name: 'ReturnLength', dir: '[out, opt]', desc: 'Receives required or actual size.' },
    ],
    retval: 'NTSTATUS. STATUS_INFO_LENGTH_MISMATCH if buffer is too small.',
    href: 'https://learn.microsoft.com/windows/win32/api/winternl/nf-winternl-ntquerysysteminformation',
  },
  // user32 / gdi32
  'sendmessagew': {
    module: 'user32', badge: 'Win32',
    signature: 'LRESULT SendMessageW(\n  HWND   hWnd,\n  UINT   Msg,\n  WPARAM wParam,\n  LPARAM lParam\n);',
    description: 'Sends the specified message to a window or windows. The function does not return until the target window procedure has processed the message.',
    params: [
      { name: 'hWnd', dir: '[in]', desc: 'Handle to the window, or HWND_BROADCAST.' },
      { name: 'Msg', dir: '[in]', desc: 'Message identifier (WM_*).' },
      { name: 'wParam', dir: '[in]', desc: 'Additional message-specific information.' },
      { name: 'lParam', dir: '[in]', desc: 'Additional message-specific information.' },
    ],
    retval: 'The return value of the window procedure.',
    href: 'https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-sendmessagew',
  },
  'postmessagew': {
    module: 'user32', badge: 'Win32',
    signature: 'BOOL PostMessageW(\n  HWND   hWnd,\n  UINT   Msg,\n  WPARAM wParam,\n  LPARAM lParam\n);',
    description: 'Places a message in the message queue associated with the thread that created the specified window and returns without waiting.',
    params: [
      { name: 'hWnd', dir: '[in, opt]', desc: 'Window handle or HWND_BROADCAST or NULL.' },
      { name: 'Msg', dir: '[in]', desc: 'Message identifier.' },
      { name: 'wParam', dir: '[in]', desc: 'Additional message information.' },
      { name: 'lParam', dir: '[in]', desc: 'Additional message information.' },
    ],
    retval: 'Non-zero on success, zero on failure.',
    href: 'https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-postmessagew',
  },
  'createwindowexw': {
    module: 'user32', badge: 'Win32',
    signature: 'HWND CreateWindowExW(\n  DWORD     dwExStyle,\n  LPCWSTR   lpClassName,\n  LPCWSTR   lpWindowName,\n  DWORD     dwStyle,\n  int       X, int Y,\n  int       nWidth, int nHeight,\n  HWND      hWndParent,\n  HMENU     hMenu,\n  HINSTANCE hInstance,\n  LPVOID    lpParam\n);',
    description: 'Creates an overlapped, pop-up, or child window with an extended window style.',
    params: [
      { name: 'dwExStyle', dir: '[in]', desc: 'Extended window style (WS_EX_*).' },
      { name: 'lpClassName', dir: '[in, opt]', desc: 'Registered class name or atom.' },
      { name: 'lpWindowName', dir: '[in, opt]', desc: 'Window name (title bar text).' },
      { name: 'dwStyle', dir: '[in]', desc: 'Window style (WS_OVERLAPPEDWINDOW, etc.).' },
      { name: 'X, Y', dir: '[in]', desc: 'Initial position. CW_USEDEFAULT for default.' },
      { name: 'nWidth, nHeight', dir: '[in]', desc: 'Initial size. CW_USEDEFAULT for default.' },
      { name: 'hWndParent', dir: '[in, opt]', desc: 'Parent window handle.' },
      { name: 'hMenu', dir: '[in, opt]', desc: 'Menu handle or child identifier.' },
      { name: 'hInstance', dir: '[in, opt]', desc: 'Module instance handle.' },
      { name: 'lpParam', dir: '[in, opt]', desc: 'WM_CREATE data pointer.' },
    ],
    retval: 'Window handle, or NULL on failure.',
    href: 'https://learn.microsoft.com/windows/win32/api/winuser/nf-winuser-createwindowexw',
  },
  'regopenkeyexw': {
    module: 'advapi32', badge: 'Win32',
    signature: 'LSTATUS RegOpenKeyExW(\n  HKEY    hKey,\n  LPCWSTR lpSubKey,\n  DWORD   ulOptions,\n  REGSAM  samDesired,\n  PHKEY   phkResult\n);',
    description: 'Opens the specified registry key.',
    params: [
      { name: 'hKey', dir: '[in]', desc: 'Handle to an open registry key, or predefined key (HKEY_LOCAL_MACHINE, etc.).' },
      { name: 'lpSubKey', dir: '[in, opt]', desc: 'Subkey name.' },
      { name: 'ulOptions', dir: '[in]', desc: 'Reserved, must be 0.' },
      { name: 'samDesired', dir: '[in]', desc: 'Access mask (KEY_READ, KEY_WRITE, etc.).' },
      { name: 'phkResult', dir: '[out]', desc: 'Receives handle to the opened key.' },
    ],
    retval: 'ERROR_SUCCESS (0) on success, or a Win32 error code.',
    href: 'https://learn.microsoft.com/windows/win32/api/winreg/nf-winreg-regopenkeyexw',
  },
  'regqueryvalueexw': {
    module: 'advapi32', badge: 'Win32',
    signature: 'LSTATUS RegQueryValueExW(\n  HKEY    hKey,\n  LPCWSTR lpValueName,\n  LPDWORD lpReserved,\n  LPDWORD lpType,\n  LPBYTE  lpData,\n  LPDWORD lpcbData\n);',
    description: 'Retrieves the type and data for the specified value name associated with an open registry key.',
    params: [
      { name: 'hKey', dir: '[in]', desc: 'Open registry key handle.' },
      { name: 'lpValueName', dir: '[in, opt]', desc: 'Name of the registry value.' },
      { name: 'lpReserved', dir: '[in, opt]', desc: 'Reserved, must be NULL.' },
      { name: 'lpType', dir: '[out, opt]', desc: 'Receives the data type (REG_SZ, REG_DWORD, etc.).' },
      { name: 'lpData', dir: '[out, opt]', desc: 'Buffer for the data.' },
      { name: 'lpcbData', dir: '[in, out, opt]', desc: 'Size of lpData, receives bytes written.' },
    ],
    retval: 'ERROR_SUCCESS on success, ERROR_MORE_DATA if buffer too small.',
    href: 'https://learn.microsoft.com/windows/win32/api/winreg/nf-winreg-regqueryvalueexw',
  },
};

// Flat list of all known API entries for autocomplete: { token: "module!FunctionName", key, doc }
const API_SUGGESTIONS = Object.entries(WINDOWS_API_DB).map(([key, doc]) => {
  // Reconstruct canonical function name: capitalize each word segment
  const fn = key.charAt(0).toUpperCase() + key.slice(1);
  return { token: `${doc.module}!${fn}`, key, doc };
});

/**
 * FunctionCallBrowser - Manages the Function Calls tab for TTD API call queries.
 */
export default class FunctionCallBrowser {
  constructor(element) {
    this.element = element;
    this.results = [];
    this.selectedEventId = null;
    this.selectedEventIds = new Set();
    this.isLoading = false;
    this.hasSearched = false;
    this.lastQuery = '';
    this.lastMeta = 'Search for a symbol such as kernel32!LoadLibraryW or paste a target address.';

    this.form = this.element?.querySelector('#function-call-form') ?? null;
    this.input = this.element?.querySelector('#function-call-input') ?? null;
    this.submitButton = this.element?.querySelector('#function-call-submit') ?? null;
    this.loadingIndicator = this.element?.querySelector('#function-call-loading') ?? null;
    this.resultsList = this.element?.querySelector('#function-call-results') ?? null;
    this.resultsMeta = this.element?.querySelector('#function-call-results-meta') ?? null;
    this.selectAllButton = this.element?.querySelector('#function-call-select-all') ?? null;
    this.clearSelectionButton = this.element?.querySelector('#function-call-clear-selection') ?? null;
    this.syncButton = this.element?.querySelector('#function-call-sync') ?? null;
    this.selectedCount = this.element?.querySelector('#function-call-selected-count') ?? null;
    this.detailTitle = this.element?.querySelector('#function-call-detail-title') ?? null;
    this.detailBody = this.element?.querySelector('#function-call-detail-body') ?? null;
    this.jumpButton = this.element?.querySelector('#function-call-jump') ?? null;

    // Autocomplete list is appended to document.body so it escapes all stacking contexts
    this.autocompleteList = document.createElement('ul');
    this.autocompleteList.id = 'function-call-autocomplete';
    this.autocompleteList.className = 'function-call-autocomplete';
    this.autocompleteList.setAttribute('role', 'listbox');
    this.autocompleteList.setAttribute('aria-label', 'API suggestions');
    document.body.appendChild(this.autocompleteList);

    this._acIndex = -1; // keyboard-active suggestion index
    this._acItems = []; // current filtered suggestions

    this.setupEventListeners();
    this.render();
  }

  setupEventListeners() {
    this.form?.addEventListener('submit', (event) => {
      event.preventDefault();
      this.handleSubmit();
    });

    this.resultsList?.addEventListener('click', (event) => {
      const item = event.target.closest('[data-function-call-id]');
      if (!item) return;
      const eventId = item.dataset.functionCallId;
      if (event.target.closest('.function-call-select input')) {
        this.toggleEventSelection(eventId);
        return;
      }

      this.selectEvent(eventId);
    });

    this.selectAllButton?.addEventListener('click', () => {
      this.selectAllEvents();
    });

    this.clearSelectionButton?.addEventListener('click', () => {
      this.clearSelection();
    });

    this.syncButton?.addEventListener('click', () => {
      this.syncSelectedToTimeline();
    });

    this.jumpButton?.addEventListener('click', () => {
      const selectedEvent = this.getSelectedEvent();
      if (!selectedEvent || !this.onJumpToEvent) return;
      this.onJumpToEvent(selectedEvent);
    });

    // Autocomplete
    this.input?.addEventListener('input', () => {
      this._updateAutocomplete();
      this.resetSelectionForInputDraft();
    });
    this.input?.addEventListener('focus', () => this._updateAutocomplete());
    this.input?.addEventListener('blur', () => {
      // Delay so click on list item fires first
      setTimeout(() => this._closeAutocomplete(), 150);
    });
    this.input?.addEventListener('keydown', (e) => {
      if (!this.autocompleteList?.classList.contains('open')) return;
      if (e.key === 'ArrowDown') {
        e.preventDefault();
        this._acIndex = Math.min(this._acIndex + 1, this._acItems.length - 1);
        this._highlightAcItem();
      } else if (e.key === 'ArrowUp') {
        e.preventDefault();
        this._acIndex = Math.max(this._acIndex - 1, -1);
        this._highlightAcItem();
      } else if (e.key === 'Enter' || e.key === 'Tab') {
        if (this._acIndex >= 0 && this._acItems[this._acIndex]) {
          e.preventDefault();
          this._selectAcItem(this._acItems[this._acIndex]);
        } else {
          this._closeAutocomplete();
        }
      } else if (e.key === 'Escape') {
        this._closeAutocomplete();
      }
    });
    this.autocompleteList?.addEventListener('mousedown', (e) => {
      const li = e.target.closest('li[data-ac-index]');
      if (li) {
        const idx = parseInt(li.dataset.acIndex, 10);
        if (!isNaN(idx) && this._acItems[idx]) {
          this._selectAcItem(this._acItems[idx]);
        }
      }
    });
  }

  _updateAutocomplete() {
    const raw = this.input?.value ?? '';
    // Extract the part after the last '!' if present; otherwise use the whole value
    const bangIdx = raw.lastIndexOf('!');
    const searchTerm = bangIdx >= 0 ? raw.slice(bangIdx + 1).toLowerCase() : raw.toLowerCase();
    const modulePrefix = bangIdx >= 0 ? raw.slice(0, bangIdx + 1).toLowerCase() : '';

    if (searchTerm.length < 1 && !modulePrefix) {
      this._closeAutocomplete();
      return;
    }

    const filtered = API_SUGGESTIONS.filter((s) => {
      const tokenLower = s.token.toLowerCase();
      if (modulePrefix) {
        // Must match module prefix AND function part
        return tokenLower.startsWith(modulePrefix) && tokenLower.slice(bangIdx + 1).includes(searchTerm);
      }
      return tokenLower.includes(searchTerm);
    }).slice(0, 12);

    this._acItems = filtered;
    this._acIndex = -1;

    if (filtered.length === 0 || raw === filtered[0]?.token) {
      this._closeAutocomplete();
      return;
    }

    const highlight = (text, term) => {
      if (!term) return this.escapeHtml(text);
      const idx = text.toLowerCase().indexOf(term.toLowerCase());
      if (idx < 0) return this.escapeHtml(text);
      return this.escapeHtml(text.slice(0, idx))
        + `<span class="ac-match">${this.escapeHtml(text.slice(idx, idx + term.length))}</span>`
        + this.escapeHtml(text.slice(idx + term.length));
    };

    this.autocompleteList.innerHTML = filtered.map((s, i) => {
      const fnPart = s.token.slice(s.token.indexOf('!') + 1);
      const mod = s.doc.module;
      return `<li role="option" data-ac-index="${i}">${highlight(fnPart, searchTerm)} <span class="ac-module">${this.escapeHtml(mod)}</span></li>`;
    }).join('');

    // Position fixed relative to input
    const rect = this.input.getBoundingClientRect();
    this.autocompleteList.style.left = `${rect.left}px`;
    this.autocompleteList.style.top = `${rect.bottom + 2}px`;
    this.autocompleteList.style.width = `${rect.width}px`;

    this.autocompleteList.classList.add('open');
  }

  _highlightAcItem() {
    const items = this.autocompleteList?.querySelectorAll('li') ?? [];
    items.forEach((li, i) => li.classList.toggle('active', i === this._acIndex));
    if (this._acIndex >= 0) items[this._acIndex]?.scrollIntoView({ block: 'nearest' });
  }

  _selectAcItem(suggestion) {
    if (this.input) this.input.value = suggestion.token;
    this._closeAutocomplete();
    this.input?.focus();
  }

  _closeAutocomplete() {
    this.autocompleteList?.classList.remove('open');
    this._acIndex = -1;
    this._acItems = [];
  }

  async handleSubmit() {
    if (!this.onSearch || this.isLoading) {
      return;
    }

    const query = this.input?.value.trim() ?? '';
    if (!query) {
      return;
    }

    this.setLoading(true);
    this.hasSearched = true;
    this.lastQuery = query;
    this.lastMeta = 'Searching trace call events...';
    this.render();

    try {
      const response = await this.onSearch(query);
      this.results = Array.isArray(response?.events) ? response.events : [];
      this.selectedEventId = this.results[0]?.eventId ?? null;
      this.selectedEventIds = new Set(this.selectedEventId ? [this.selectedEventId] : []);

      const returnedCount = typeof response?.returnedCount === 'number'
        ? response.returnedCount
        : this.results.length;
      const totalCount = typeof response?.totalCount === 'number'
        ? response.totalCount
        : this.results.length;

      this.lastMeta = totalCount > 0
        ? `${returnedCount} result${returnedCount === 1 ? '' : 's'} returned (${totalCount} match${totalCount === 1 ? '' : 'es'} total)`
        : (response?.message ?? 'No matching function-call events found.');

      const firstEvent = this.getSelectedEvent();
      if (firstEvent && this.onEventSelect) {
        this.onEventSelect(firstEvent);
      }
    } catch (error) {
      this.results = [];
      this.selectedEventId = null;
      this.selectedEventIds = new Set();
      this.lastMeta = error?.message ?? 'Function-call search failed.';
    } finally {
      this.setLoading(false);
      this.render();
      this.focusInput();
    }
  }

  setLoading(loading) {
    this.isLoading = loading;
    if (this.input) {
      this.input.disabled = loading;
    }
    if (this.loadingIndicator) {
      this.loadingIndicator.classList.toggle('visible', loading);
    }
    if (this.submitButton) {
      this.submitButton.disabled = loading;
      this.submitButton.textContent = loading ? 'Searching...' : 'Search';
    }
  }

  setActive(active) {
    if (active) {
      this.focusInput();
    }
  }

  focusEventById(eventId) {
    if (!eventId) return false;
    const match = this.results.find((event) => event.eventId === eventId);
    if (!match) return false;

    this.selectedEventId = eventId;
    this.selectedEventIds.add(eventId);
    this.render();

    if (this.resultsList) {
      const items = Array.from(this.resultsList.querySelectorAll('[data-function-call-id]'));
      const item = items.find((node) => node.dataset.functionCallId === eventId);
      item?.scrollIntoView({ block: 'nearest', behavior: 'smooth' });
    }
    return true;
  }

  focusInput() {
    this.input?.focus();
  }

  selectEvent(eventId) {
    this.selectedEventId = eventId;
    if (eventId != null) {
      this.selectedEventIds.add(eventId);
    }
    const selectedEvent = this.getSelectedEvent();
    if (selectedEvent && this.onEventSelect) {
      this.onEventSelect(selectedEvent);
    }
    this.render();
  }

  toggleEventSelection(eventId) {
    if (!eventId) return;

    if (this.selectedEventIds.has(eventId)) {
      this.selectedEventIds.delete(eventId);
    } else {
      this.selectedEventIds.add(eventId);
      this.selectedEventId = eventId;
    }

    if (this.selectedEventId == null && this.selectedEventIds.size > 0) {
      this.selectedEventId = this.selectedEventIds.values().next().value;
    }

    if (this.selectedEventId != null && !this.selectedEventIds.has(this.selectedEventId)) {
      this.selectedEventId = this.selectedEventIds.size > 0
        ? this.selectedEventIds.values().next().value
        : (this.results[0]?.eventId ?? null);
    }

    const selectedEvent = this.getSelectedEvent();
    if (selectedEvent && this.onEventSelect) {
      this.onEventSelect(selectedEvent);
    }

    this.render();
  }

  selectAllEvents() {
    this.selectedEventIds = new Set(this.results.map((event) => event.eventId));
    if (this.selectedEventId == null && this.results.length > 0) {
      this.selectedEventId = this.results[0].eventId;
    }
    this.render();
  }

  clearSelection() {
    this.selectedEventIds.clear();
    this.render();
  }

  resetSelectionForInputDraft() {
    if (this.selectedEventIds.size === 0) {
      return;
    }
    this.selectedEventIds.clear();
    this.renderResults();
  }

  getSelectedEvents() {
    if (this.selectedEventIds.size === 0) return [];
    return this.results.filter((event) => this.selectedEventIds.has(event.eventId));
  }

  syncSelectedToTimeline() {
    if (!this.onSyncEvents) return;
    const selectedEvents = this.getSelectedEvents();
    if (selectedEvents.length === 0) return;
    this.onSyncEvents(selectedEvents);
  }

  getSelectedEvent() {
    if (this.results.length === 0) {
      return null;
    }

    return this.results.find((event) => event.eventId === this.selectedEventId)
      ?? this.results[0]
      ?? null;
  }

  render() {
    this.renderResults();
    this.renderDetail();
  }

  renderResults() {
    if (this.resultsMeta) {
      this.resultsMeta.textContent = this.lastMeta;
    }

    if (!this.resultsList) {
      return;
    }

    if (this.results.length === 0) {
      const safeQuery = this.escapeHtml(this.lastQuery || 'current query');
      const isSearchInFlight = this.isLoading;
      const isNoResultsDone = !this.isLoading && this.hasSearched;
      const emptyTitle = this.isLoading
        ? 'Searching API call events...'
        : (isNoResultsDone ? 'No API calls returned' : 'No function-call events loaded');
      const emptyCopy = this.isLoading
        ? `Running function-call search for ${safeQuery}. It may take a while.`
        : (isNoResultsDone
          ? `Search completed for ${safeQuery}. No matching API calls were found in the trace.`
          : 'Try a symbol like kernel32!LoadLibraryExW, ntdll!NtMapViewOfSection, or a target address.');
      const emptyTitleClass = (isSearchInFlight || isNoResultsDone)
        ? 'function-call-empty-title function-call-empty-title-warning'
        : 'function-call-empty-title';
      this.resultsList.innerHTML = `
        <div class="function-call-empty">
          <div class="${emptyTitleClass}">${emptyTitle}</div>
          <div class="function-call-empty-copy">${emptyCopy}</div>
        </div>
      `;
      return;
    }

    const selectedEvent = this.getSelectedEvent();
    this.resultsList.innerHTML = this.results.map((event) => {
      const active = event.eventId === selectedEvent?.eventId;
      const checked = this.selectedEventIds.has(event.eventId);
      const major = event.startPosition?.major;
      const minor = event.startPosition?.minor ?? 0;
      const position = major != null
        ? `${BigInt(major).toString(16).toUpperCase()}:${Number(minor).toString(16).toUpperCase()}`
        : '?';
      return `
        <div
          class="function-call-result${active ? ' active' : ''}"
          data-function-call-id="${this.escapeHtml(event.eventId)}"
        >
          <div class="function-call-result-head">
            <label class="function-call-result-select" title="Select this event for timeline sync">
              <input type="checkbox" ${checked ? 'checked' : ''}>
            </label>
            <span class="function-call-result-function">${this.escapeHtml(event.function ?? event.rawFunction ?? '(unknown)')}</span>
            <span class="function-call-result-thread">TID ${this.escapeHtml(String(event.threadId ?? '?'))}</span>
          </div>
          <div class="function-call-result-meta">
            <span>${this.escapeHtml(event.module || 'no module')}</span>
            <span>${this.escapeHtml(position)}</span>
          </div>
          <div class="function-call-result-summary">${this.escapeHtml(event.summary ?? '')}</div>
        </div>
      `;
    }).join('');

    this.renderSelectionState();
  }

  renderSelectionState() {
    const selectedCount = this.getSelectedEvents().length;
    if (this.selectedCount) {
      this.selectedCount.textContent = `${selectedCount} selected`;
    }
    if (this.syncButton) {
      this.syncButton.disabled = selectedCount === 0;
    }
    if (this.clearSelectionButton) {
      this.clearSelectionButton.disabled = selectedCount === 0;
    }
    if (this.selectAllButton) {
      this.selectAllButton.disabled = this.results.length === 0;
    }
  }

  renderDetail() {
    if (!this.detailBody || !this.detailTitle || !this.jumpButton) {
      return;
    }

    const selectedEvent = this.getSelectedEvent();
    if (!selectedEvent) {
      this.detailTitle.textContent = 'Event Details';
      this.detailBody.innerHTML = `
        <div class="function-call-empty">
          <div class="function-call-empty-title">Select a function-call event</div>
          <div class="function-call-empty-copy">The backend will return call metadata and parameters for the current trace query.</div>
        </div>
      `;
      this.jumpButton.disabled = true;
      return;
    }

    this.detailTitle.textContent = selectedEvent.function ?? selectedEvent.rawFunction ?? 'Event Details';
    this.jumpButton.disabled = false;
    const selectedApiDoc = this.getApiDocForEvent(selectedEvent);

    // x64 calling convention: first 4 args in registers, rest on stack
    const REG_NAMES = ['rcx', 'rdx', 'r8', 'r9'];
    const parameters = Array.isArray(selectedEvent.parameters) && selectedEvent.parameters.length > 0
      ? selectedEvent.parameters.map((param, index) => {
          const isReg = index < 4;
          const docParam = selectedApiDoc?.params?.[index] ?? null;
          const stackOffsetHex = isReg ? '' : `0x${(0x28 + ((index - 4) * 8)).toString(16)}`;
          const hintText = docParam?.name ?? (isReg ? null : `stack+${stackOffsetHex}`);
          const hintTitle = docParam?.desc ?? '';
          const hintDir = docParam?.dir ? `<span class="function-call-param-dir">${this.escapeHtml(docParam.dir)}</span>` : '';
          const hintHtml = hintText
            ? `<span class="function-call-param-hint" title="${this.escapeHtml(hintTitle)}">${this.escapeHtml(hintText)}${hintDir}</span>`
            : '';
          const descHtml = hintTitle
            ? `<div class="function-call-param-desc">${this.escapeHtml(hintTitle)}</div>`
            : '';
          const label = isReg
            ? `arg${index} <span class="function-call-param-reg">${REG_NAMES[index]}</span>`
            : `arg${index} <span class="function-call-param-stack">stack</span>`;
          return `
          <div class="function-call-kv-row function-call-param-row">
            <span class="function-call-kv-key">${label}${hintHtml}</span>
            ${descHtml}
            <span class="function-call-kv-value">${this.escapeHtml(String(param))}</span>
          </div>`;
        }).join('')
      : '<div class="function-call-kv-row"><span class="function-call-kv-key">args</span><span class="function-call-kv-value">(none)</span></div>';

    this.detailBody.innerHTML = `
      <div class="function-call-detail-group">
        <div class="function-call-kv-row"><span class="function-call-kv-key">Module</span><span class="function-call-kv-value">${this.escapeHtml(selectedEvent.module || '—')}</span></div>
        <div class="function-call-kv-row"><span class="function-call-kv-key">Thread</span><span class="function-call-kv-value">${this.escapeHtml(String(selectedEvent.threadId ?? '—'))}</span></div>
        <div class="function-call-kv-row"><span class="function-call-kv-key">Start</span><span class="function-call-kv-value">${this.escapeHtml(this._fmtPos(selectedEvent.startPosition))}</span></div>
        <div class="function-call-kv-row"><span class="function-call-kv-key">End</span><span class="function-call-kv-value">${this.escapeHtml(this._fmtPos(selectedEvent.endPosition))}</span></div>
        <div class="function-call-kv-row"><span class="function-call-kv-key">Function</span><span class="function-call-kv-value">${this.escapeHtml(selectedEvent.functionAddress ?? '—')}</span></div>
        <div class="function-call-kv-row"><span class="function-call-kv-key">Return</span><span class="function-call-kv-value">${this.escapeHtml(selectedEvent.returnAddress ?? '—')}</span></div>
        <div class="function-call-kv-row"><span class="function-call-kv-key">Value</span><span class="function-call-kv-value">${this.escapeHtml(selectedEvent.returnValue ?? '—')}</span></div>
        <div class="function-call-kv-row"><span class="function-call-kv-key">Event Type</span><span class="function-call-kv-value">${this.escapeHtml(String(selectedEvent.eventType ?? '—'))}</span></div>
      </div>
      <div class="function-call-detail-group">
        <div class="function-call-detail-section-title">Parameters</div>
        ${parameters}
      </div>
      <div class="function-call-detail-group">
        <div class="function-call-detail-section-title">Summary</div>
        <pre class="function-call-summary">${this.escapeHtml(selectedEvent.summary ?? '(no summary)')}</pre>
      </div>
      ${this.renderApiDoc(selectedEvent)}
    `;
  }

  getApiDocForEvent(event) {
    const rawFn = event?.function ?? event?.rawFunction ?? '';
    const fnName = rawFn.includes('!') ? rawFn.slice(rawFn.indexOf('!') + 1) : rawFn;
    if (!fnName) return null;
    return WINDOWS_API_DB[fnName.toLowerCase()] ?? null;
  }

  renderApiDoc(event) {
    const rawFn = event?.function ?? event?.rawFunction ?? '';
    // Strip module prefix: "kernel32!LoadLibraryW" -> "LoadLibraryW"
    const fnName = rawFn.includes('!') ? rawFn.slice(rawFn.indexOf('!') + 1) : rawFn;
    const doc = this.getApiDocForEvent(event);
    if (!doc) return '';

    const badgeClass = doc.badge === 'NT' ? 'api-doc-badge-nt' : 'api-doc-badge-win32';

    const paramsHtml = doc.params.length > 0
      ? `<table class="api-doc-param-table">${doc.params.map((p) => `
          <tr>
            <td>${this.escapeHtml(p.name)}</td>
            <td>${this.escapeHtml(p.dir)}</td>
            <td>${this.escapeHtml(p.desc)}</td>
          </tr>`).join('')}
        </table>`
      : '<span style="color:#7b8d96;font-size:12px">No parameters.</span>';

    const remarksHtml = doc.remarks
      ? `<div class="api-doc-section-title">Remarks</div><div class="api-doc-remarks">${this.escapeHtml(doc.remarks)}</div>`
      : '';

    return `
      <div class="function-call-detail-group api-doc">
        <div class="api-doc-title">${this.escapeHtml(fnName)}<span class="api-doc-badge ${badgeClass}">${this.escapeHtml(doc.badge)}</span></div>
        <div class="api-doc-description">${this.escapeHtml(doc.description)}</div>
        <div class="api-doc-section-title">Syntax</div>
        <pre class="api-doc-signature">${this.escapeHtml(doc.signature)}</pre>
        <div class="api-doc-section-title">Parameters</div>
        ${paramsHtml}
        <div class="api-doc-section-title">Return Value</div>
        <div class="api-doc-retval">${this.escapeHtml(doc.retval)}</div>
        ${remarksHtml}
        <a class="api-doc-msdn-link" href="${this.escapeHtml(doc.href)}" target="_blank" rel="noopener noreferrer">&#8599; View on Microsoft Learn</a>
      </div>
    `;
  }

  escapeHtml(text) {
    return String(text)
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#39;');
  }

  _fmtPos(pos) {
    if (!pos?.major) return '—';
    const major = BigInt(pos.major).toString(16).toUpperCase();
    const minor = Number(pos.minor ?? 0);
    return `${major}:${minor.toString(16).toUpperCase()}`;
  }

  onSearch = null;
  onEventSelect = null;
  onJumpToEvent = null;
  onSyncEvents = null;
}